### ISSUE TITLE
Database schema is not available in this project...

### ISSUE THREAD

**Issue by das-aeri** [bquadre/xcollections#2]
Database schema is not available in this project
Can you please send me Database schema to run this project?

**Comment by deyeni2001** [comment]
I thought so at first. Its a asp.net core application. The DB is auto-generated. Its code first entity framework. Set the parameters and you are in.

**Comment by das-aeri** [comment]
> I thought so at first. Its a asp.net core application. The DB is auto-generated. Its code first entity framework. Set the parameters and you are in.
Actually i am getting error while first running- 
An error occurred while starting the application.
AggregateException: One or more errors occurred. (Invalid object name 'AspNetRoles'.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

SqlException: Invalid object name 'AspNetRoles'.
System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__108_0(Task<SqlDataReader> result)

AggregateException: One or more errors occurred. (Invalid object name 'AspNetRoles'.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
System.Threading.Tasks.Task.Wait()
Softmax.XCollections.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs

**Comment by adeyeni** [comment]
Create a db. Call it "coop" in your sql server. Create a user in your db in appropriate roles and control over the coop db.
Go and change the user , password and db in the app.json file. 
Go to your nuget package manager console
Run the command "update-database"
After it runs. Run the app. Check your db. You will see that the db has been populated.

Migrate

**Comment by das-aeri** [comment]
DB created, connection string also changed but still
Getting error from -
===============================
public void Configure(IApplicationBuilder app)        {
            try
            {
                _methods.ConfigureDelegate(app);
            }
            catch (Exception ex)
            {
                if (ex is TargetInvocationException)
                {
                    ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
                }
                throw;
            }
        }
-------------------------------------------Exception Details------------------------------------------------
An error occurred while starting the application.
AggregateException: One or more errors occurred. (Invalid object name 'AspNetRoles'.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

SqlException: Invalid object name 'AspNetRoles'.
System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__108_0(Task<SqlDataReader> result)

AggregateException: One or more errors occurred. (Invalid object name 'AspNetRoles'.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
System.Threading.Tasks.Task.Wait()
Softmax.XCollections.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
+
            CreateRoles(serviceProvider).Wait();
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.ApplicationInsights.HostingStartup.ApplicationInsightsLoggerStartupFilter+<>c__DisplayClass0_1.<Configure>b__0(IApplicationBuilder builder)
Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter+<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by deyeni2001** [comment]
Change the connection string in file CollectionsDbContext.cs too.

**Comment by bquadre** [comment]
Sorry for delay response It is due to my tight schedule 
Comment out this part first CreateRoles(serviceProvider).Wait(); then run update-database
After successful database migration you can  now "uncomment" it. I hope it works

**Comment by das-aeri** [comment]
thanks... Code is running now...
Comment out this part CreateRoles(serviceProvider).Wait();  and then rerun code is working...
i have checked this application...but loan re payment option and some other important functionality is not available...
Thanks for your support..
